blank_issues_enabled: false
contact_links:
  - name: Questions & Feature Requests
    url: https://github.com/codebar-ag/laravel-prerender/issues/new
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/codebar-ag/laravel-prerender/security/policy
    about: Learn how to notify us for sensitive bugs
